version: "3.8"

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    command: --auth-provider simple
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dozzle-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.barron.agency`)"  
      - "traefik.http.routers.dozzle.entrypoints=web"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle-secure.rule=Host(`dozzle.barron.agency`)"  
      - "traefik.http.routers.dozzle-secure.entrypoints=websecure"
      - "traefik.http.routers.dozzle-secure.tls=true"

networks:
  proxy:
    external: true  # Verwende ein externes Netzwerk, das von Traefik verwendet wird
