services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    command: --auth-provider simple
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dozzle-data:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dozzle.rule=Host(`dozzle.barron.agency`)'
      - 'traefik.http.routers.dozzle.entrypoints=websecure'
      - 'traefik.http.routers.dozzle.tls.certresolver=letsencrypt'
      - 'traefik.http.services.dozzle.loadbalancer.server.port=8080'

networks:
  proxy:
    external: false
    name: proxy
