services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    command: --auth-provider simple
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dozzle-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-web.rule=Host(`dozzle.barron.agency`)"
      - "traefik.http.routers.chatbot-web.entrypoints=web"
      - "traefik.http.services.chatbot-web.loadbalancer.server.port=8080"
      - "traefik.http.routers.chatbot-web-secure.rule=Host(`dozzle.barron.agency`)"
      - "traefik.http.routers.chatbot-web-secure.entrypoints=websecure"
      - "traefik.http.routers.chatbot-web-secure.tls=true"

networks:
  proxy:
    external: false
    name: proxy
